// CODE GENERATED USING MAKOTEMPLATES.ORG, DO NOT EDIT.
// FILE_VERSION: {db["version"]}

// MIC19 - Modulo de Interface de Controle
#define CAN_SIGNATURE_MIC19 240
// CAN_FILTER_MSG_STATE - Module state report
#define CAN_FILTER_MSG_STATE 8
#define CAN_FILTER_MSG_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_STATE_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_STATE_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_STATE_STATE_BYTE 1 //<!" State code
#define CAN_FILTER_MSG_STATE_STATE_TYPE "u8"
#define CAN_FILTER_MSG_STATE_STATE_UNITS ""
#define CAN_FILTER_MSG_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_FILTER_MSG_STATE_ERROR_TYPE "u8"
#define CAN_FILTER_MSG_STATE_ERROR_UNITS ""
// CAN_FILTER_MSG_MOTOR - Motor controller parameters
#define CAN_FILTER_MSG_MOTOR 9
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_MOTOR_MOTOR_BYTE 1 //<!" Motor state
#define CAN_FILTER_MSG_MOTOR_MOTOR_TYPE "bitfield"
#define CAN_FILTER_MSG_MOTOR_MOTOR_UNITS ""
#define CAN_FILTER_MSG_MOTOR_MOTOR_MOTOR_ON_BIT 0
#define CAN_FILTER_MSG_MOTOR_MOTOR_DMS_ON_BIT 1
#define CAN_FILTER_MSG_MOTOR_D_BYTE 2 //<!" Motor Duty Cycle
#define CAN_FILTER_MSG_MOTOR_D_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_D_UNITS "%"
#define CAN_FILTER_MSG_MOTOR_I_BYTE 3 //<!" Motor Soft Start
#define CAN_FILTER_MSG_MOTOR_I_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_I_UNITS "%"
// CAN_FILTER_MSG_PUMPS - Pumps controller parameters
#define CAN_FILTER_MSG_PUMPS 10
#define CAN_FILTER_MSG_PUMPS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_PUMPS_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_PUMPS_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_PUMPS_PUMPS_BYTE 1 //<!" Pumps state
#define CAN_FILTER_MSG_PUMPS_PUMPS_TYPE "bitfield"
#define CAN_FILTER_MSG_PUMPS_PUMPS_UNITS ""
#define CAN_FILTER_MSG_PUMPS_PUMPS_PUMP1_BIT 0
#define CAN_FILTER_MSG_PUMPS_PUMPS_PUMP2_BIT 1
#define CAN_FILTER_MSG_PUMPS_PUMPS_PUMP3_BIT 2
// CAN_FILTER_MSG_MPTTS - Mppts controller parameters
#define CAN_FILTER_MSG_MPTTS 11
#define CAN_FILTER_MSG_MPTTS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_MPTTS_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_MPTTS_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_MPTTS_MPPTS_ON_BYTE 1 //<!" MPPTs state
#define CAN_FILTER_MSG_MPTTS_MPPTS_ON_TYPE "bitfield"
#define CAN_FILTER_MSG_MPTTS_MPPTS_ON_UNITS ""
#define CAN_FILTER_MSG_MPTTS_MPPTS_ON_MPPTS_ON_BIT 0
#define CAN_FILTER_MSG_MPTTS_POT_BYTE 2 //<!" MPPTs maximum power limitation
#define CAN_FILTER_MSG_MPTTS_POT_TYPE "u8"
#define CAN_FILTER_MSG_MPTTS_POT_UNITS "%"
// CAN_FILTER_MSG_MCS - MCS controller parameters
#define CAN_FILTER_MSG_MCS 12
#define CAN_FILTER_MSG_MCS_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_MCS_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_MCS_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_MCS_BOAT_ON_BYTE 1 //<!" Boat state
#define CAN_FILTER_MSG_MCS_BOAT_ON_TYPE "bitfield"
#define CAN_FILTER_MSG_MCS_BOAT_ON_UNITS ""
#define CAN_FILTER_MSG_MCS_BOAT_ON_BOAT_ON_BIT 0



// MAM19 - Modulo de Acionamento do Motor
#define CAN_SIGNATURE_MAM19 190
// CAN_FILTER_MSG_STATE - Module state report
#define CAN_FILTER_MSG_STATE 16
#define CAN_FILTER_MSG_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_STATE_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_STATE_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_STATE_STATE_BYTE 1 //<!" State code
#define CAN_FILTER_MSG_STATE_STATE_TYPE "u8"
#define CAN_FILTER_MSG_STATE_STATE_UNITS ""
#define CAN_FILTER_MSG_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_FILTER_MSG_STATE_ERROR_TYPE "u8"
#define CAN_FILTER_MSG_STATE_ERROR_UNITS ""
// CAN_FILTER_MSG_MOTOR - Motor controller parameters
#define CAN_FILTER_MSG_MOTOR 17
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_MOTOR_D_BYTE 1 //<!" Motor Duty Cycle
#define CAN_FILTER_MSG_MOTOR_D_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_D_UNITS "%"
#define CAN_FILTER_MSG_MOTOR_I_BYTE 2 //<!" Motor Soft Start
#define CAN_FILTER_MSG_MOTOR_I_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_I_UNITS "%"



// MAB19 - Modulo de Acionamento das Bombas de Porao
#define CAN_SIGNATURE_MAB19 230



// MSC19 - Modulo de Sensores CAN
#define CAN_SIGNATURE_MSC19 250
// CAN_FILTER_MSG_STATE - Module state report
#define CAN_FILTER_MSG_STATE 32
#define CAN_FILTER_MSG_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_STATE_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_STATE_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_STATE_STATE_BYTE 1 //<!" State code
#define CAN_FILTER_MSG_STATE_STATE_TYPE "u8"
#define CAN_FILTER_MSG_STATE_STATE_UNITS ""
#define CAN_FILTER_MSG_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_FILTER_MSG_STATE_ERROR_TYPE "u8"
#define CAN_FILTER_MSG_STATE_ERROR_UNITS ""
// CAN_FILTER_MSG_ADC - ADC values
#define CAN_FILTER_MSG_ADC 33
#define CAN_FILTER_MSG_ADC_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_ADC_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_ADC_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_ADC_AVG_L_BYTE 1 //<!" Avg byte low
#define CAN_FILTER_MSG_ADC_AVG_L_TYPE "u8"
#define CAN_FILTER_MSG_ADC_AVG_L_UNITS ""
#define CAN_FILTER_MSG_ADC_AVG_H_BYTE 2 //<!" Avg byte high
#define CAN_FILTER_MSG_ADC_AVG_H_TYPE "u8"
#define CAN_FILTER_MSG_ADC_AVG_H_UNITS ""
#define CAN_FILTER_MSG_ADC_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_FILTER_MSG_ADC_MIN_L_TYPE "u8"
#define CAN_FILTER_MSG_ADC_MIN_L_UNITS ""
#define CAN_FILTER_MSG_ADC_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_FILTER_MSG_ADC_MIN_H_TYPE "u8"
#define CAN_FILTER_MSG_ADC_MIN_H_UNITS ""
#define CAN_FILTER_MSG_ADC_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_FILTER_MSG_ADC_MAX_L_TYPE "u8"
#define CAN_FILTER_MSG_ADC_MAX_L_UNITS ""
#define CAN_FILTER_MSG_ADC_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_FILTER_MSG_ADC_MAX_H_TYPE "u8"
#define CAN_FILTER_MSG_ADC_MAX_H_UNITS ""



// MCS19 - Modulo de Carregamento do Sistema
#define CAN_SIGNATURE_MCS19 200
// CAN_FILTER_MSG_STATE - Module state report
#define CAN_FILTER_MSG_STATE 256
#define CAN_FILTER_MSG_STATE_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_STATE_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_STATE_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_STATE_STATE_BYTE 1 //<!" State code
#define CAN_FILTER_MSG_STATE_STATE_TYPE "u8"
#define CAN_FILTER_MSG_STATE_STATE_UNITS ""
#define CAN_FILTER_MSG_STATE_ERROR_BYTE 2 //<!" Error code
#define CAN_FILTER_MSG_STATE_ERROR_TYPE "u8"
#define CAN_FILTER_MSG_STATE_ERROR_UNITS ""
// CAN_FILTER_MSG_START_STAGES - Boat charging // Boat on
#define CAN_FILTER_MSG_START_STAGES 516
#define CAN_FILTER_MSG_START_STAGES_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_START_STAGES_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_START_STAGES_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_START_STAGES_MAIN_RELAY_BYTE 1 //<!" Boat on/off
#define CAN_FILTER_MSG_START_STAGES_MAIN_RELAY_TYPE "bitfield"
#define CAN_FILTER_MSG_START_STAGES_MAIN_RELAY_UNITS ""
#define CAN_FILTER_MSG_START_STAGES_MAIN_RELAY_MAIN_RELAY_BIT 0
#define CAN_FILTER_MSG_START_STAGES_CHARGE_RELAY_BYTE 2 //<!" Boat Charging
#define CAN_FILTER_MSG_START_STAGES_CHARGE_RELAY_TYPE "bitfield"
#define CAN_FILTER_MSG_START_STAGES_CHARGE_RELAY_UNITS ""
#define CAN_FILTER_MSG_START_STAGES_CHARGE_RELAY_CHARGE_RELAY_BIT 0
// CAN_FILTER_MSG_BAT - battery voltage values
#define CAN_FILTER_MSG_BAT 258
#define CAN_FILTER_MSG_BAT_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_BAT_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_BAT_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_BAT_AVG_L_BYTE 1 //<!" Avg byte low
#define CAN_FILTER_MSG_BAT_AVG_L_TYPE "u8"
#define CAN_FILTER_MSG_BAT_AVG_L_UNITS ""
#define CAN_FILTER_MSG_BAT_AVG_H_BYTE 2 //<!" Avg byte high
#define CAN_FILTER_MSG_BAT_AVG_H_TYPE "u8"
#define CAN_FILTER_MSG_BAT_AVG_H_UNITS ""
#define CAN_FILTER_MSG_BAT_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_FILTER_MSG_BAT_MIN_L_TYPE "u8"
#define CAN_FILTER_MSG_BAT_MIN_L_UNITS ""
#define CAN_FILTER_MSG_BAT_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_FILTER_MSG_BAT_MIN_H_TYPE "u8"
#define CAN_FILTER_MSG_BAT_MIN_H_UNITS ""
#define CAN_FILTER_MSG_BAT_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_FILTER_MSG_BAT_MAX_L_TYPE "u8"
#define CAN_FILTER_MSG_BAT_MAX_L_UNITS ""
#define CAN_FILTER_MSG_BAT_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_FILTER_MSG_BAT_MAX_H_TYPE "u8"
#define CAN_FILTER_MSG_BAT_MAX_H_UNITS ""
// CAN_FILTER_MSG_CAP - capacitor bank voltage values
#define CAN_FILTER_MSG_CAP 259
#define CAN_FILTER_MSG_CAP_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_CAP_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_CAP_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_CAP_AVG_L_BYTE 1 //<!" Avg byte low
#define CAN_FILTER_MSG_CAP_AVG_L_TYPE "u8"
#define CAN_FILTER_MSG_CAP_AVG_L_UNITS ""
#define CAN_FILTER_MSG_CAP_AVG_H_BYTE 2 //<!" Avg byte high
#define CAN_FILTER_MSG_CAP_AVG_H_TYPE "u8"
#define CAN_FILTER_MSG_CAP_AVG_H_UNITS ""
#define CAN_FILTER_MSG_CAP_MIN_L_BYTE 3 //<!" Min byte low
#define CAN_FILTER_MSG_CAP_MIN_L_TYPE "u8"
#define CAN_FILTER_MSG_CAP_MIN_L_UNITS ""
#define CAN_FILTER_MSG_CAP_MIN_H_BYTE 4 //<!" Min byte high
#define CAN_FILTER_MSG_CAP_MIN_H_TYPE "u8"
#define CAN_FILTER_MSG_CAP_MIN_H_UNITS ""
#define CAN_FILTER_MSG_CAP_MAX_L_BYTE 5 //<!" Max byte low
#define CAN_FILTER_MSG_CAP_MAX_L_TYPE "u8"
#define CAN_FILTER_MSG_CAP_MAX_L_UNITS ""
#define CAN_FILTER_MSG_CAP_MAX_H_BYTE 6 //<!" Max byte low
#define CAN_FILTER_MSG_CAP_MAX_H_TYPE "u8"
#define CAN_FILTER_MSG_CAP_MAX_H_UNITS ""



// MT19 - Modulo Tacometro
#define CAN_SIGNATURE_MT19 255



