// CODE GENERATED USING MAKOTEMPLATES.ORG, DO NOT EDIT.
// FILE_VERSION: {db["version"]}

// MIC17 - Modulo de Interface de Controle
#define CAN_SIGNATURE_MIC17 9
// CAN_FILTER_MSG_MOTOR - Motor controller parameters
#define CAN_FILTER_MSG_MOTOR 10
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_SIGNATURE_UNITS ""
#define CAN_FILTER_MSG_MOTOR_D_BYTE 1 //<!" Motor Duty Cycle
#define CAN_FILTER_MSG_MOTOR_D_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_D_UNITS "%"
#define CAN_FILTER_MSG_MOTOR_I_BYTE 2 //<!" Motor Soft Start
#define CAN_FILTER_MSG_MOTOR_I_TYPE "u8"
#define CAN_FILTER_MSG_MOTOR_I_UNITS "%"



