// CODE GENERATED USING MAKOTEMPLATES.ORG, DO NOT EDIT.
// FILE_VERSION: {db["version"]}


// MIC17 - Modulo de Interface de Controle
#define CAN_SIGNATURE_MIC17 10
// MIC17 - MOTOR - Motor controller parameters
#define CAN_MSG_MIC17_MOTOR_ID 9
#define CAN_MSG_MIC17_MOTOR_LENGTH 4
#define CAN_MSG_MIC17_MOTOR_SIGNATURE_BYTE 0 //<!" Senders signature
#define CAN_MSG_MIC17_MOTOR_SIGNATURE_TYPE "u8"
#define CAN_MSG_MIC17_MOTOR_SIGNATURE_UNITS ""
#define CAN_MSG_MIC17_MOTOR_MOTOR_BYTE 1 //<!" Switches and states
#define CAN_MSG_MIC17_MOTOR_MOTOR_TYPE "bitfield"
#define CAN_MSG_MIC17_MOTOR_MOTOR_UNITS ""
#define CAN_MSG_MIC17_MOTOR_MOTOR_MOTOR_ON_BIT 0
#define CAN_MSG_MIC17_MOTOR_D_RAW_BYTE 2 //<!" Motor Duty Cycle
#define CAN_MSG_MIC17_MOTOR_D_RAW_TYPE "u8"
#define CAN_MSG_MIC17_MOTOR_D_RAW_UNITS "%"
#define CAN_MSG_MIC17_MOTOR_I_RAW_BYTE 3 //<!" Motor Soft Start
#define CAN_MSG_MIC17_MOTOR_I_RAW_TYPE "u8"
#define CAN_MSG_MIC17_MOTOR_I_RAW_UNITS "%"


